#!/bin/bash

# Example command-equivalent representation of the Oxford Nanopore
# re-basecalling configuration used for this study.
#
# ONT basecalling software version: 7.6.7+de8939544
# Client-server API version: 21.0.0
# Configuration: dna_r10.4.1_e8.2_400bps_5khz_sup.cfg
# Minimum Q-score: 10
# Barcode kit: SQK-RBK114-24
#
# Re-basecalling was performed through a Dorado environment.

ont_basecall_client \
  --config dna_r10.4.1_e8.2_400bps_5khz_sup.cfg \
  --input_path /path/to/pod5_input \
  --save_path /path/to/basecalling_output \
  --min_qscore 10 \
  --barcode_kits SQK-RBK114-24
